ALTER TABLE users ADD COLUMN IF NOT EXISTS discord_id VARCHAR(30) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS discord_name VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS discord_avatar VARCHAR(500);
